# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: main
    paths:
      - '**.xlsx'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: ls
    # - uses: ./actions/xl2resx-action
    # - run: ls
    - run: pwd
    # - run: cd output
    - run: ls
    
    - name: docker
      run: |
        docker build . -t xl2resx
        docker-compose up -d
        docker ps -a
    - name: Make resx
      run: |
        docker exec xl2resx_container python3 xl2resx.py
        ls
    - run: git status
    - run: sudo mv ./output_/* ./output/
    - name: commit
      run: |
        git config --local user.email "localization[bot]@user.noreply.github.com"
        git config --local user.name "localization[bot]"
        git add ./output
        git status
        git commit -m "Updates localization changes"
    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openpyxl 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        
