name: xlsx to resx

on:
  push:
    branches: main
    #paths:
    #  - '**.xlsx'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: docker
      run: |
        mkdir out
        docker build . -t xl2resx
        docker-compose up -d

    - name: make the resources of test
      if: hashFiles('test.xlsx') != ''
      run: |
        docker exec xl2resx_container python3 xl2resx.py test.xlsx
        sudo mv ./out/*.resx ./output/

    - name: make the resources of FineLocalizer
      if: hashFiles('FineLocalizer.xlsx') != ''
      run: |
        docker exec xl2resx_container python3 xl2resx.py FineLocalizer.xlsx
        sudo mv ./out/*.resx ./FineLocalizer/Lang/

    - name: make the resources of CalibrationTool
      if: hashFiles('CalibrationTool.xlsx') != ''
      run: |
        docker exec xl2resx_container python3 xl2resx.py CalibrationTool.xlsx
        sudo mv ./out/*.resx ./CalibrationTool/Lang/

    - name: make the resources of CommonUtils
      if: hashFiles('CommonUtils.xlsx') != ''
      run: |
        docker exec xl2resx_container python3 xl2resx.py CommonUtils.xlsx
        sudo mv ./out/*.resx ./CommonUtils/Lang/

    - name: commit
      run: |
        git config --local user.email "dev@cogaplex.com"
        git config --local user.name "CoPickDev[bot]"
        git add .
        git status
        git commit -m "Updates localization changes"
        sudo rm -r ./out

    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
