name: xlsx to resx

on:
  push:
    branches: main
    #paths:
    #  - '**.xlsx'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: docker
      run: |
        mkdir out
        mkdir -p ./test/Lang
        docker build . -t xl2resx
        docker-compose up
        docker ps 

    - name: move the resources of test
      if: hasFiles('test.xlsx') != ''
      run: |
        ls ./out
        sudo mv ./out/*.resx ./test/Lang/
        sudo rm ./out/*.resx
        ls ./out

    - run: |
        sudo mv ./out/* ./$FineLocalizerPath/
        ls ./out/${FineLocalizerPath}
        sudo mv ./out/${CommonUtilsPath}*.resx ./$Sheet1/Lang/
      env:
        FineLocalizerPath: output
        CommonUtilsPath: Sheet1
        CalibrationToolPath: CalibrationTool

    - name: commit
      run: |
        git config --local user.email "dev@cogaplex.com"
        git config --local user.name "CoPickDev[bot]"
        git add ./output
        git status
        git commit -m "Updates localization changes"

    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
